### ISSUE TITLE
propagate updates

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#187]
State of the world.

(1) people don’t know that they need to propagate their projects
(2) people don’t know how to propagate projects

So, we need to do the following:
  (1) put a warning in neurodataviz so people know their data isn’t propogated
      (a) point them to the documentation about propagation (@alexbaden)
      (b) tell them to use UI to propagate project (@alexbaden)
      (c) document propagate (@kunallillaney)

  (2) get UI button that calls propagate service to work (@randburns)

The UI gives status as to the propagation state 0, 1, running
Eventually we need:
   (3) progress bar (estimated based on the current z-index being processed @alexbaden)
   (4) propagation to be restartable. (what’s up here @kunallillaney)

@randalburns @alexbaden @kunallillaney

**Comment by willgray** [comment]
@jovo - By UI you mean some version of the web console?  Last we talked about this, there were some data security questions we punted on and also some new documentation needed to make it clear when a user should/should not propagate.  Running through the webconsole instead of an exposed restful interface will help.

It would be cool if we supported bidirectional on-the-fly propagation, even if it's potentially very slow. For computer vision applications (e.g., cell detection, synapses, ...we often will write an intermediate output that would be cool to visualize, but may have additional data to write and so don't propagate.  If this isn't clear, maybe talk about on Monday?

**Comment by jovo** [comment]
@willgray i copied and pasted randal's comment here.

**Comment by alexbaden** [comment]
@willgray - I believe OCP already does dynamic up sampling / downsampling
for annotation channels that are NOT propagated.

**Comment by kunallillaney** [comment]
@jovo @randalburns @alexbaden Documentation for propagate exists here http://docs.neurodata.io/open-connectome/api/propagate_api.html. 

Propagation is also restartable. The way it restarts is to wipe out everything apart from the base resolution and start over again. Caveat: Very rarely propagation breaks down in the under propagation state, say the celery process crashed because the database became unreachable, at this stage we require manual intervention to restart it.

@willgray We did talk about this. With the new branch you cannot propagate a project if it is marked readonly(this is true from the REST'ful interface and should be done so from the GUI as well to avoid confusion). To make a project solid you propagate it and mark it readonly. The only way you can mark a project "not readonly" is from the Console. This ensure that you own the project before you can mark it "not readonly" and only then can you call propagate on it. Let me know if this is unclear and we can discuss it more.

**Comment by alexbaden** [comment]
Propagate status check added to the latest ndv beta: http://brainviz1.cs.jhu.edu/ndv/kharris15apical/em,annos/
