### ISSUE TITLE
a simple way for people to determine when ocp is down

### ISSUE THREAD

**Issue by jovo** [neurodata/ndstore#210]
even a link to http://isup.me/openconnecto.me/ or something would be fine.
i think it would be very helpful.

**Comment by kunallillaney** [comment]
I found this but we will have install it. https://cachethq.io/. @Aeusman had some found something the other day as well.

**Comment by jovo** [comment]
i support whatever makes your life easier :)

**Comment by jovo** [comment]
@Aeusman suggested this: https://gist.github.com/willjohnson/6313986
seems less "mature" than cachethq?

**Comment by kunallillaney** [comment]
@jovo cachethq is the open-source install/DIY version of this https://www.statuspage.io/tour. It is a bit pricey with $30/month service but has features like scheduled downtime, API level statuses, integration with slack, status of 3rd party infrastructure providers(eg amazon s3) and more importantly not maintenance/update required. I frankly don't have the bandwidth to install/own cachethq but I think we do need a mature solution(or at least attempt to have one). Here is what I recommend:
- If @Aeusman/anyeone else is willing to own cachethq then we can install in on brainapps and try it out. This is ideal as we don't pay anything and can use whatever option we like.
- Otherwise we can try out statuspage and see how that goes(not sure how much work will it require to use all the features). But if this feels expensive or does not work out we can fall to the last "less mature" option which @Aeusman suggested.
What do you think?

**Comment by jovo** [comment]
@micro-alex first, it would be ideal for me if you changed your github handle to @micro-alex
second, wanna check and see how much easier statuspage is over cachet in terms of your time commitment? if its a big difference, $30/month is worth it.  alternately, it might be worth starting with cachet and transfering over to statuspage, if that is relatively easy.

@Aeusman

**Comment by Aeusman** [comment]
@jovo Changing user names [causes problems](https://help.github.com/articles/what-happens-when-i-change-my-username/).
I'm willing to poke around with cachet since I don't have a ton on my plate right now, I'll let you know what the difference looks like, but based on the install docs for cachet it doesn't seem to bad.

**Comment by jovo** [comment]
ok, @aeusman is ok for now :+1:
let us know about cachet...

On Thu, Feb 4, 2016 at 9:28 AM, Alex Eusman <notifications@github.com>
wrote:

> @jovo <https://github.com/jovo> Changing user names causes problems
> <https://help.github.com/articles/what-happens-when-i-change-my-username/>
> .
> I'm willing to poke around with cachet since I don't have a ton on my
> plate right now, I'll let you know what the difference looks like, but
> based on the install docs for cachet it doesn't seem to bad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/210#issuecomment-179869989>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io

**Comment by kunallillaney** [comment]
We are now using statuspage. @Aeusman close this issue when we have a prototype working.

**Comment by kunallillaney** [comment]
Look at #411
