### ISSUE TITLE
RAMON objects tied to resolution - can we decouple?

### ISSUE THREAD

**Issue by willgray** [neurodata/ndstore#215]
Going forward in the new branch it would be convenient to access RAMON object data independent of resolution.  This is helpful for neurodata viz, graph construction, scientific queries...

Resolution would still be needed when getting/putting paint (dense or voxel data), but shouldn't be required for other operations, I assert.

For example, if a pixel is labeled 42 in an annotation channel, this will map to a particular set of metadata regardless of resolution.  I think this more clear for humans and enables functionality, plus avoids weird conflicts.

Discuss?  

@kunallillaney @randalburns @alexbaden @j6k4m8 @jovo

**Comment by alexbaden** [comment]
This has been resolved, pushed to both microns and master, and deployed to dsp029. I only put in place the fix for getting an ID at a single voxel. The query for getting all IDs in a cube still needs to be fixed. But, let's validate that modifying the coordinates is a good idea first (just in case there are any weird issues).

**Comment by willgray** [comment]
this is cool!
