### ISSUE TITLE
Usage of Dockerfile

### ISSUE THREAD

**Issue by jstriebel** [neurodata/ndstore#272]
Hello,
Is it possible to deploy instances of the ndstore with Docker? Which Dockerfile should be used therefore and how? (e.g. [this](https://github.com/neurodata/ndstore/blob/microns/setup/docker_config/Dockerfile)?)
Any information about such a setup would be helpful.

Cheers, Jonathan

**Comment by kunallillaney** [comment]
@jstriebel Which ndstore configuration do you want to use and what I/O performance is required and what is the size of your dataset? ndstore can be deployed with MySQL, Cassandra or Redis (DyanmoDB and Riak are partially supported and not tested) with an optional S3 backend for various deployment requirements.
That Dockerfile is the right one to use but I have not tested it. I would recommend using an EC2 instance type i2.8xlarge(or any of the i2 series with the dedicated SSD's) for deployment since that currently mirrors our current setup(we use HDD's not SSD's on our local cluster). You can use the ndstore_install.sh script to install the stack from scratch.
Both the Dockerfile and the install script install the MySQL backend.

**Comment by kunallillaney** [comment]
@jstriebel Can we close this issue?

**Comment by jstriebel** [comment]
@kunallillaney Thanks for your explanations, they helped a lot. It was mainly about which Dockerfile to use. At the moment it is only for testing the ndstore with a low load.
And sorry for the late reply! Closing this now.
