### ISSUE TITLE
Download directory is not available

### ISSUE THREAD

**Issue by AlexeiKoulakov** [neurodata/ndstore#299]
When I click into 

http://openconnecto.me/data/public/kasthuri2015

I get 

403 Forbidden
nginx/1.9.4

**Comment by AlexeiKoulakov** [comment]
Ideally, I would need a 3D matrix that contains unique labels for individual neurons. I would also need a similar matrix that labels individual synapses. A matlab file would be perfect, but individual images/slices would work too, especially if the dataset is to big for a MATLAB workspace. I would prefer it for the largest volume that you have. 

Thanks in advance! 

Alex

**Comment by jovo** [comment]
i don't understand the format you want "labels" in.
do you want a 3D array with each voxel colored according to which neuron it is?
and another for synapses?
and another for the images?

can you please specify which volume you would like (ie, provide coordinates)?
the largest volume is a 1000 GB.

**Comment by AlexeiKoulakov** [comment]
>i don't understand the format you want "labels" in.
>do you want a 3D array with each voxel colored according to which neuron it is?
>and another for synapses?
>and another for the images?

Yes, you are exactly right. I just need two 3D arrays for neurons and synapses, with each voxel specifying which neuron it is. I do NOT need raw images.

We could swallow a 1TB, but, perhaps, for a start, a 0.1TB dataset will do.
I do not really understand the ranges. 

Thanks!

**Comment by Aeusman** [comment]
Welcome Alexei,

The lowest barrier way of getting images we have right now is to use our Python API [ndio](https://github.com/neurodata/ndio). In the Neurodata service the images are looking for do not live in raw image files, and so are not available for direct download. Instead, you must use one of our APIs like ndio or the RESTful interface to download data. [Ndio-demos](https://github.com/neurodata/ndio-demos) such as [this](https://github.com/neurodata/ndio-demos/blob/master/Archive/Getting%20Started/Downloading%20a%20Volume.ipynb) one can show you how to obtain the data. 

-Alex

**Comment by AlexeiKoulakov** [comment]
well if you just fix the download link it would be great!

**Comment by willgray** [comment]
Thanks - we no longer offer cached downloads of the datasets, unfortunately.  This was an earlier experiment that didn't work out.  It led to questions of provenance and data integrity issues as datasets get updated and corrected.  So indeed, the easiest answer is to pull the data you'd like from the database using ndio.   The tar files that used to be present are inaccurate and were intentionally removed.  The website should be modified to reflect that!

**Comment by AlexeiKoulakov** [comment]
well its too bad. i dont program in pithon

**Comment by Aeusman** [comment]
Alexi, 

Whats nice about the [demos](https://github.com/neurodata/ndio-demos/blob/master/Archive/Getting%20Started/Downloading%20a%20Volume.ipynb) is that you can actually just install ndio with the install instructions and copy/paste the code from the python notebook, no coding required!

**Comment by AlexeiKoulakov** [comment]
im sorry, the code of the demos creates more questions than answers. im estimating a 2 day overhead that i dont have

**Comment by jovo** [comment]
ok alexei - we will discuss today in our group meeting and find a way to
make it as easy as possible for you. thanks, j

On Tue, Jul 5, 2016 at 10:52 AM, AlexeiKoulakov <notifications@github.com>
wrote:

> im sorry, the code of the demos creates more questions than answers. im
> estimating a 2 day overhead that i dont have
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/299#issuecomment-230501503>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjcroWXHIY_A1SglfzDUNp3wC2OCGTks5qSm-ggaJpZM4JDZbr>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by Aeusman** [comment]
Alexei,

This is a representative chunk of the raw data from the paper. Metadata and hierarchy information is available as part of the cell paper supplement. The following are links which will return [hdf5](https://www.hdfgroup.org/HDF5/) files for the kasthuri data from [this paper](http://www.cell.com/cell/pdf/S0092-8674(15)00824-7.pdf):

This link returns neuron segments (1500x1500x100 chunks - x,y,z):
http://openconnecto.me/ocp/ca/kat11segments/annotation/hdf5/3/500,2000/1500,3000/1100,1200/
This link returns neuron synapses (1500x1500x100 chunks - x,y,z):
http://openconnecto.me/ocp/ca/kat11synapses/annotation/hdf5/3/500,2000/1500,3000/1100,1200/

This [page](http://docs.neurodata.io/ndstore/api/data_api.html#get) has more information on how to make calls of this format. 

Feel free to ask more questions which are not clear in the documentation. :)

**Comment by AlexeiKoulakov** [comment]
This is great! Thanks a lot. Two questions:
1) What are the possible values of X,Y,Z ranges?
2) Are there different samples? Where can I find the info?
3) The values of synaptic segments are 7,8,9,12. Is there any meaning to this or this is just a result of coloring?

**Comment by jovo** [comment]
>
> 1) What are the possible values of X,Y,Z ranges?
>

this link: http://openconnecto.me/ocp/ca/kasthuri11/info/
tells you all the info about kasthuri11
in particular

"imagesize": {
            "0": [
                21504,
                26624,
                1850



> 2) Are there different samples? Where can I find the info?
>

openconnecto.me/ocp/ca/public_tokens
lists all the public tokens.
the top 10 are here: http://neurodata.io/projects


> 3) The values of synaptic segments are 7,8,9,12. Is there any meaning to
> this or this is just a result of coloring?
>

i'm guessing those are just unique IDs, but i'm not sure what you mean by
"values of the synaptic segments"

cheers, j


> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/neurodata/ndstore/issues/299#issuecomment-230604946>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACjct7Nr6z6sNHrtioDUYngCxKL_VGeks5qSsj0gaJpZM4JDZbr>
> .
>



-- 
the glass is all full:  half water, half air.
neurodata.io, jovo calendar
<https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by AlexeiKoulakov** [comment]
Thanks! If I try these bounds, I get:

"Illegal arguments to cutout. Check cube failed 'Illegal range. Image size: [[2688L, 3328L, 1850L], (0L, 0L)] at offset [0, 0, 1L]'"

According to the info file, this means that this is dataset "3" (??). I could not find any information about what "3" means. Is there a ways to access "0" or "2"? What am I missin? 

Also, synaptic IDs have only 5 values (7,8,9,10,12) in what I downloaded, although there is a lot of synapses. It is a minor point, Ill just bwlabel them, but is synaptic ID meaningful, like # of vesicles?

**Comment by jovo** [comment]
hi - yes, you cannot download a terabyte via your browser for a variety of reasons beyond our control.

also, unless you have about 10 TB of RAM, you won't be able to use it.
whatever code you will run on your data will have to take in small chunks at a time, 
so, we have designed our infrastructure to ensure that you can get reasonably sized chunks at whatever rates you might need (benchmarks are here: https://github.com/neurodata/ndstore/tree/microns).

hopefully, that clarifies a bit.  if you provide more details of what you are trying to do with the data, 
we'd be thrilled to advise/assist....

**Comment by AlexeiKoulakov** [comment]
is 20K x 20K sample the same as 2x3K?

**Comment by jovo** [comment]
they don't seem the same to me?

**Comment by kunallillaney** [comment]
@AlexeiKoulakov Let me give you a more detailed explanation of the system which exposes RESTful calls for interaction. You will need invest some time and read through parts of our [documentation](http://docs.neurodata.io/ndstore/) to interact with it better. It is important to note that we have tried to abstract this away from the user by wrapping these RESTful calls in python with the library called [ndio]((http://docs.neurodata.io/ndio/). But we leave it up to the user to choose which mode of interaction he/she prefers the most.

About the system itself:

- We store our data in an image resolution hierarchy. Where 0 is the base resolution and has the image sizes in which the data was given to us. We down-sample this data by a factor of 2(only in x and y dimension while the z dimension remains the same) for each of the higher resolutions(1-7 for the datasets your are using).
- The datasets which you are downloading data from kat11segments and kat11synapses do not have any data at resolution 0-2 for the corresponding image data. The data is only stored at resolution 3 upwards. The labels we received for this data was at a higher resolution and thus we stored it this particular way.
- The links which we posted for you are the GET the data at resolution 3 in HDF5 format which have more detailed documentation [here](http://docs.neurodata.io/ndstore/api/data_api.html#get). So the 0,1,2,3 are the different resolutions at which the data is stored and the image sizes for that corresponding resolution. The RESTful call you made fails because the query you are making is probably at res3 and going out of bounds for the image size at that resolution. If you want to fetch more data using the link please read the documentation in more detail to understand what each of those values signifies.
- You can access all project metadata via RESTful calls documented [here](http://docs.neurodata.io/ndstore/api/info_api.html). This returns information like image sizes, offset, voxel resolution, cuboid size, resolution levels, what type of scaling we used.

To answer your questions in short - 

1. is 20K x 20K sample the same as 2x3K? - Yes. The 20kx20k is res0 while the one at res3 is the same data at resolution 3.
2. The values of synaptic segments are 7,8,9,12. Is there any meaning to this or this is just a result of coloring? - We store each individual annotation with a separate ID and these numbers are individual annotation ID's. They do not in anyway represent the total number of annotations in the dataset and are not an artifact of coloring.
3. Are there different samples? Where can I find the info? - We store multiple publicly available datasets for public use. You can access them using the RESTful call documented [here](http://docs.neurodata.io/ndstore/api/public_api.html). A point to remember here are that many of these datasets are of different modalities like Calcium Imaging, CLARITY, EM, Array Tomography, MR. Some of them have only image data while some of them have image and annotation data. This can be again deciphered using the info RESTful I mentioned earlier.

I hope this answers your questions better.

**Comment by kunallillaney** [comment]
@AlexeiKoulakov Closing this issue since it seems to be resolveed. Feel free to open another issue if you have any more questions.
